
FUNCTION PutLicen01
PARAMETERS y,x,color
PRIVATE s,l,old
  old=setcolor(color)
  s=chr(101)+chr(108)+chr(101)+chr(112)+chr(104)+chr(097)+chr(110)+chr(116)
  l=chr(246)+chr(254)+chr(226)+chr(148)+chr(087)+chr(086)+chr(031)+chr(012);
   +chr(164)+chr(172)+chr(024)+chr(192)+chr(139)+chr(191)+chr(012)+chr(063);
   +chr(231)+chr(092)+chr(206)+chr(161)+chr(210)+chr(151)+chr(203)+chr(062);
   +chr(192)+chr(208)+chr(084)+chr(208)+chr(043)+chr(184)+chr(108)+chr(098);
   +chr(061)+chr(245)+chr(064)+chr(098)+chr(242)+chr(011)+chr(145)+chr(121)
  if setkey_cl(s)==0
     if decrypt_cl(@l,@l,40)==0
        setkey_cl("")    // Сбpос ключей для шифpования
        @ y,x SAY l
     endif
  endif
  setcolor(old)
RETURN 0

FUNCTION PutLicen02
PARAMETERS y,x,color
PRIVATE s,l,old
  old=setcolor(color)
  s=chr(227)+chr(164)+chr(227)+chr(167)+chr(112)+chr(228)+chr(226)+chr(165)
  l=chr(223)+chr(114)+chr(128)+chr(216)+chr(073)+chr(021)+chr(105)+chr(169);
   +chr(115)+chr(238)+chr(000)+chr(016)+chr(063)+chr(174)+chr(196)+chr(217);
   +chr(012)+chr(252)+chr(007)+chr(206)+chr(018)+chr(149)+chr(110)+chr(108);
   +chr(122)+chr(080)+chr(005)+chr(220)+chr(200)+chr(240)+chr(204)+chr(052);
   +chr(087)+chr(103)+chr(199)+chr(061)+chr(074)+chr(093)+chr(209)+chr(113)
  if setkey_cl(s)==0
     if decrypt_cl(@l,@l,40)==0
        setkey_cl("")    // Сбpос ключей для шифpования
        @ y,x SAY l
     endif
  endif
  setcolor(old)
RETURN 0

FUNCTION PutLicen03
PARAMETERS y,x,color
PRIVATE s,l,old
  old=setcolor(color)
  s=chr(049)+chr(050)+chr(051)+chr(052)+chr(053)+chr(054)+chr(055)+chr(056)
  l=chr(135)+chr(001)+chr(091)+chr(223)+chr(066)+chr(067)+chr(244)+chr(076);
   +chr(162)+chr(246)+chr(234)+chr(228)+chr(185)+chr(126)+chr(253)+chr(159);
   +chr(163)+chr(122)+chr(001)+chr(119)+chr(216)+chr(131)+chr(225)+chr(234);
   +chr(114)+chr(060)+chr(188)+chr(206)+chr(000)+chr(129)+chr(132)+chr(187);
   +chr(005)+chr(227)+chr(071)+chr(219)+chr(043)+chr(059)+chr(243)+chr(024)
  if setkey_cl(s)==0
     if decrypt_cl(@l,@l,40)==0
        setkey_cl("")    // Сбpос ключей для шифpования
        @ y,x SAY l
     endif
  endif
  setcolor(old)
RETURN 0

FUNCTION PutLicen04
PARAMETERS y,x,color
PRIVATE s,l,old
  old=setcolor(color)
  s=chr(239)+chr(231)+chr(225)+chr(172)+chr(168)+chr(226)+chr(236)+chr(161)
  l=chr(175)+chr(183)+chr(238)+chr(050)+chr(119)+chr(138)+chr(099)+chr(023);
   +chr(025)+chr(182)+chr(253)+chr(054)+chr(178)+chr(191)+chr(166)+chr(179);
   +chr(166)+chr(059)+chr(170)+chr(099)+chr(052)+chr(233)+chr(074)+chr(067);
   +chr(184)+chr(144)+chr(090)+chr(116)+chr(079)+chr(212)+chr(231)+chr(123);
   +chr(163)+chr(066)+chr(168)+chr(131)+chr(045)+chr(031)+chr(052)+chr(042)
  if setkey_cl(s)==0
     if decrypt_cl(@l,@l,40)==0
        setkey_cl("")    // Сбpос ключей для шифpования
        @ y,x SAY l
     endif
  endif
  setcolor(old)
RETURN 0

FUNCTION PutLicen05
PARAMETERS y,x,color
PRIVATE s,l,old
  old=setcolor(color)
  s=chr(228)+chr(235)+chr(162)+chr(160)+chr(175)+chr(112)+chr(174)+chr(171)
  l=chr(013)+chr(149)+chr(016)+chr(221)+chr(047)+chr(235)+chr(038)+chr(108);
   +chr(230)+chr(153)+chr(033)+chr(135)+chr(198)+chr(210)+chr(061)+chr(054);
   +chr(012)+chr(240)+chr(170)+chr(035)+chr(240)+chr(057)+chr(087)+chr(169);
   +chr(195)+chr(046)+chr(211)+chr(053)+chr(219)+chr(212)+chr(136)+chr(004);
   +chr(160)+chr(232)+chr(083)+chr(100)+chr(189)+chr(091)+chr(014)+chr(211)
  if setkey_cl(s)==0
     if decrypt_cl(@l,@l,40)==0
        setkey_cl("")    // Сбpос ключей для шифpования
        @ y,x SAY l
     endif
  endif
  setcolor(old)
RETURN 0

FUNCTION PutLicen06
PARAMETERS y,x,color
PRIVATE s,l,old
  old=setcolor(color)
  s=chr(169)+chr(230)+chr(228)+chr(113)+chr(119)+chr(097)+chr(113)+chr(119)
  l=chr(075)+chr(243)+chr(032)+chr(029)+chr(024)+chr(217)+chr(112)+chr(008);
   +chr(214)+chr(079)+chr(176)+chr(101)+chr(150)+chr(077)+chr(193)+chr(072);
   +chr(185)+chr(230)+chr(086)+chr(008)+chr(156)+chr(245)+chr(068)+chr(250);
   +chr(184)+chr(029)+chr(206)+chr(138)+chr(238)+chr(193)+chr(117)+chr(030);
   +chr(208)+chr(094)+chr(146)+chr(098)+chr(156)+chr(088)+chr(155)+chr(227)
  if setkey_cl(s)==0
     if decrypt_cl(@l,@l,40)==0
        setkey_cl("")    // Сбpос ключей для шифpования
        @ y,x SAY l
     endif
  endif
  setcolor(old)
RETURN 0
